// build.js v2.0 - Claude Sonnet 4.5
// Production build script with Tailwind CSS compilation
// 1. Compiles and minifies Tailwind CSS
// 2. Bundles server code
// 3. Copies all public assets to dist directory

import { $ } from "bun";
import { cpSync, rmSync, existsSync, mkdirSync } from "fs";

console.log("🧹 Cleaning dist directory...");
if (existsSync("./dist")) {
  rmSync("./dist", { recursive: true, force: true });
}
mkdirSync("./dist");

// Step 1: Build Tailwind CSS (minified for production)
console.log("🎨 Building Tailwind CSS...");
await $`bunx @tailwindcss/cli -i ./public/styles/input.css -o ./public/styles/output.css --minify`;
console.log("   ✓ Tailwind CSS compiled and minified");

// Step 2: Build server bundle
console.log("🔨 Building server bundle...");
await $`bun build ./src/server.js --outdir ./dist --target bun`;
console.log("   ✓ Server bundled");

// Step 3: Copy all public assets (including the compiled CSS)
console.log("📁 Copying public assets...");
cpSync("./public", "./dist/public", { recursive: true });
console.log("   ✓ Public assets copied");

console.log("\n✅ Build complete! Ready for deployment.");
console.log("\n📦 Deployment files created in ./dist/");
console.log("   ./dist/server.js           - Bundled server");
console.log("   ./dist/public/             - Static files");
console.log("   ./dist/public/styles/      - Compiled & minified CSS");
console.log("\n🧪 To test the production build:");
console.log("   bun run start");
console.log("\n📊 Build Stats:");
console.log("   CSS: Compiled & minified with Tailwind");
console.log("   JS:  Bundled (not minified)");
```

## Project Structure

Your project should now look like this:
````your-project/
├── src/
│   ├── server.js          # Main server file
│   ├── db.js              # Database modules
│   └── ...
├── public/
│   ├── index.html         # HTML files
│   ├── app.js             # Client-side JavaScript
│   ├── styles/
│   │   ├── input.css      # Tailwind source file (you edit this)
│   │   └── output.css     # Generated by Tailwind (gitignored)
│   └── ...
├── dist/                  # Production build (gitignored)
│   ├── server.js
│   └── public/
│       └── styles/
│           └── output.css # Minified production CSS
├── dev.js                 # Development launcher
├── build.js               # Production build script
├── package.json
├── tailwind.config.js     # Tailwind configuration
└── .gitignore`;
